name: "Update normal icon"
description: Use this template to update an existing icon. Normal icons work for both light and dark themes.
title: "feat(icons): update [NAME]"
labels: ["normal-icon"]
body:
  - type: markdown
    attributes:
      value: |
        Hello and thank you for contributing to the project! Please fill out the following informations to update an existing icon in the project.
  - type: input
    id: iconName
    attributes:
      label: Icon name
      description: The name has to match the existing icon name.
      placeholder: e.g. "icon-name"
  - type: textarea
    attributes:
      label: Paste icon
      description: |
        Please paste the icon here. It will automatically upload it to github.
  - type: dropdown
    attributes:
      label: Icon type
      options:
        - SVG
        - PNG
  - type: dropdown
    attributes:
      label: Categories
      multiple: true
      options:
        - AI
        - Analytics-&-Monitoring
        - Automation
        - Browsers-&-Search
        - Cloud-&-Hosting
        - Communication
        - Community-&-Social
        - Content-Management
        - Crypto
        - Databases
        - Design
        - Development
        - Downloaders
        - E-Commerce
        - Education
        - File-Management-&-Sync
        - Finance
        - Food
        - Framework
        - Gaming
        - Hardware
        - Health
        - Home-Automation
        - Identity
        - Infrastructure
        - Library
        - Mapping-&-Location
        - Media
        - Music-&-Audio
        - Nature
        - Networking
        - News
        - Notes-&-Productivity
        - Operating-Systems
        - Organization-&-Planning
        - Programming-Language
        - Security
        - Software
        - Streaming
        - Travel
        - Version-Control
        - Video
        - Virtualization
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Add additional informations like, the reason for the update, or what has been changed.
