name: "Update light & dark icon"
description: Use this template to update an existing icon. Monochrome icons need both light and dark versions.
title: "feat(icons): update [NAME]"
labels: ["monochrome-icon"]
body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > You can now submit new icon requests and updates directly using the form available at [dashboardicons.com](https://dashboardicons.com). This is the preferred way to make submissions and allows us to instantly receive and process icon contributions. Submissions can be directly approved and published by admins or contributors of Homarr Labs.

        > [!TIP]
        > Use the dashboardicons.com submission form for faster review, approval, and publishing of your icon contributions—no need to open GitHub issues!

        > [!IMPORTANT]
        > If you would like to help review, approve, or reject icon submissions, contact us:
        > - **Discord:** https://discord.com/invite/aCsmEV5RgA
        > - **Email:** homarr-labs@proton.me
        >
        > If you want to be an admin for dashboardicons.com, tell us (via Discord or email) why you'd like to help and what you bring to the project!

        > [!WARNING]
        > If you choose to submit an "old" issue in GitHub (instead of using the dashboardicons.com form), your request may take significantly longer to be reviewed and processed.

        > [!CAUTION]
        > The current GitHub issue templates for icon submission/update are being migrated. Please use the dashboardicons.com web form for all future contributions. Submissions made via GitHub issue templates may be delayed and are not the preferred channel.

        ---

        Hello and thank you for contributing to the project! Please fill out the following informations to update an existing icon in the project.
  - type: input
    id: iconName
    attributes:
      label: Icon name
      description: The name has to be unique and should be kebab-case.
      placeholder: e.g. "icon-name"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Paste light mode icon
      description: |
        Please paste the icon here. It will automatically upload it to github. This icon should be visible on a light background.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Paste dark mode icon
      description: |
        Please paste the icon here. It will automatically upload it to github. This icon should be visible on a dark background.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Icon type
      options:
        - SVG
        - PNG
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Add additional informations like, the reason for the update, or what has been changed.
